SERVER:
  PORT: 8080
  HOST: 0.0.0.0

LOGGER:
  LEVEL: debug

DB:
  HOST: localhost
  PORT: 5432
  USER: postgres
  PASSWORD: postgres
  DB_NAME: typio
  MAX_OPEN_CONNECTIONS: 35
  MAX_IDLE_CONNECTIONS: 20
  CONN_MAX_IDLE_TIME_IN_SECONDS: 60
  CONN_MAX_LIFETIME_IN_SECONDS: 300

MIGRATIONS:
  PATH: ./migrations